src/modules/requests/interfaces/response.interface.ts
src/modules/requests/requests.controller.ts
src/modules/requests/respositories/requests.repository.ts
src/modules/requests/services/requests.service.ts

- add: get request by id api 
- add: timestamp property
- example:
- add sorting query param to get all requests
- Title: feat: get request by id 
- Project: Digiteam Inventory Platform
- Participants: @iqbal167  @ayocodingit @sandisunandar99 @rindibudiaramdhan @rhmnmbr83 @rachadiannovansyah @fajarhikmal214

[Feature] Get Request By Id API

---

src/database/migrations/1664166644328-create_requests_table.ts
src/modules/requests/entities/request.entity.ts
src/modules/requests/interfaces/request.interface.ts
src/modules/requests/requests.controller.ts
src/modules/requests/respositories/requests.repository.ts
src/modules/requests/rules/request.schema-validator.ts
src/modules/requests/services/requests.service.ts

- update available item api
- refactor module pattern
- Title: fet: update available item api
- Participants: @iqbal167

[Feature] Update Available Item API

---

.github/workflows/continuous-deployment-staging.yml

- Add continuous deployment file
- Title: Create continuous deployment
- Participants: @iqbal167 @ayocodingit @rindibudiaramdhan

Create continuous deployment

---

src/common/interfaces/api-response.interface.ts
src/entities/request.entity.ts
src/modules/requests/requests.controller.ts
src/modules/requests/requests.interface.ts
src/modules/requests/requests.repository.ts
src/modules/requests/requests.service.ts

- change code typing style for entity props
- refactor request module
- Create upload file API
- Title: tidy up request API 
- Participants: @iqbal167 @ayocodingit @sandisunandar99 @fajarhikmal214 @rachadiannovansyah

Tidy Up Request API

---

.github/workflows/continuous-deployment-staging.yml
src/common/helpers/status.ts
src/database/migrations/1664166644328-create_requests_table.ts
src/entities/request.entity.ts
src/modules/requests/requests.controller.ts
src/modules/requests/requests.interface.ts
src/modules/requests/requests.repository.ts
src/modules/requests/requests.rules.ts
src/modules/requests/requests.service.ts

- update `requests` migration column 
- add `requests` entity props
- refactor update request item api
-  upload file (list of items)
- Title: add field on update request item api
- Participants: @iqbal167 @fajarhikmal214 @ayocodingit

[Feature] Add Field on Update Request Item API 

---

src/modules/requests/requests.controller.ts
src/modules/requests/requests.interface.ts
src/modules/requests/requests.repository.ts
src/modules/requests/requests.rules.ts
src/modules/requests/requests.service.ts

- change `item_name` validation field to `requested_item`
- remove unnecessary async/await keyword
- `item_name` field use
- Title: fix: input requested_item field issue
- Participants: @iqbal167 @ayocodingit @rachadiannovansyah

[Fix Issue] item_name field use

---

src/entities/request.entity.ts
src/modules/requests/requests.service.ts
src/storage/minio/minio.service.ts

- add download method on minio client service
- add `file_url` property to request entity
- generates URL to directly download file
- Title: chore: add `file_url` field to api response  get request by id
- Participants: @iqbal167 @ayocodingit @rindibudiaramdhan @rachadiannovansyah @fajarhikmal214

[Feature] Generates URL to directly download file

---

src/common/helpers/status.ts
src/common/interfaces/pagination.interface.ts
src/modules/requests/requests.controller.ts
src/modules/requests/requests.interface.ts
src/modules/requests/requests.repository.ts
src/modules/requests/requests.rules.ts
src/modules/requests/requests.service.ts
src/storage/minio/minio.service.ts

- add sorting on findall api
- filtering with request keys
- Title: feat: sorting find result
- Participants: @iqbal167 @ayocodingit @rachadiannovansyah

[Feature] Sorting FindAll Result

---

src/app.module.ts
src/modules/files/files.controller.ts
src/modules/files/files.module.ts
src/modules/files/files.service.ts

- use one api to provide upload file and get filename
response example:
- many upload files cause inefficient api endpoint
- Title: feat: upload file
- Participants: @iqbal167 @ayocodingit @rhmnmbr83

[Feature] Upload File 

---

package-lock.json
src/common/interfaces/pagination.interface.ts
src/database/migrations/1664166644328-create_requests_table.ts
src/entities/request.entity.ts
src/modules/requests/requests.controller.ts
src/modules/requests/requests.interface.ts
src/modules/requests/requests.repository.ts
src/modules/requests/requests.rules.ts
src/modules/requests/requests.service.ts

- add request replacement evidence
- add pickup evidence 
- Title: feat: evidence api
- Project: Digiteam Invenatris Platform
- Participants: @iqbal167 @ayocodingit

[Feature] Update Evidence API

---

src/common/helpers/status.ts
src/modules/requests/requests.controller.ts
src/modules/requests/requests.interface.ts
src/modules/requests/requests.rules.ts
src/modules/requests/requests.service.ts

- change `pickup_date` data type on update interface
- Title: fix: pickup_date data type 
- Participants: @iqbal167 @ayocodingit @rindibudiaramdhan @indraprasetya154 @rhmnmbr83

[Fix] Interface Data Type

---

src/modules/requests/requests.controller.ts
src/modules/requests/requests.module.ts
src/modules/requests/requests.rules.ts
src/modules/requests/requests.service.ts

- change update filename
- using `POST /files/upload` api to get filename and send it with `PATCH request/:id/filename`
- add  filter with status, request_type, division
- Title: refactor update filename api
- Project: Digiteam Inventaris Platform 
- Participants: @iqbal167 @ayocodingit @muhamadabduh

[Refactor] Update Filename API

---

src/modules/requests/requests.module.ts
src/modules/requests/requests.repository.ts
src/modules/requests/requests.rules.ts

- Add filter findAll result by `request_type`, `division`, and `status`
- refactoring update api
- Title: feat: filter `findAll` result
- Participants: @iqbal167 @ayocodingit @sandisunandar99 @muhamadabduh

[Feature] Filter FindAll Result

---

src/common/helpers/upload.ts

- add: valid mime-type for image/jpeg and image/png
- for upload evidence file
- Title: add: valid mime-type
- Participants: @iqbal167 @ayocodingit @azophy

[Feature] File Upload | Valid Mime Type

---

src/modules/requests/requests.repository.ts

- result condition for user and admin
- fail result for user and admin
- Title: fix: isAdmin result
- Participants: @iqbal167 @azophy @muhamadabduh

[Fix] isAdmin Result

---

package-lock.json
package.json
src/entities/request.entity.ts
src/modules/files/files.controller.ts
src/modules/files/files.module.ts
src/modules/files/files.service.ts
src/modules/requests/requests.service.ts
src/storage/minio/minio.service.ts

- handling download file from to minio server (indirect download)
- minio server is private so frontend app doesn't have access to direct download (policy issue)
- Title: feat: get file api
- Participants: @iqbal167 @ayocodingit

[Feature] Get File API

---

src/modules/files/files.controller.ts
src/modules/files/files.service.ts
src/storage/minio/minio.service.ts

- refactor file download handler 
- clean code
- Title: refactor: check file is exist
- Participants: @iqbal167 @ayocodingit @sandisunandar99 @rhmnmbr83

[Refactor] Check File is Exist

---

.github/workflows/continuous-deployment-staging.yml

- add git ops MR
- Title: add gitops staging
- Participants: @iqbal167 @ayocodingit @rhmnmbr83 @feriahmad @sandisunandar99 @liondy @rachadiannovansyah

[Workflows] Staging

---

.github/workflows/continuous-deployment-staging.yml
src/common/helpers/upload.ts
src/modules/requests/requests.interface.ts
src/modules/requests/requests.module.ts
src/modules/requests/requests.repository.ts
src/modules/requests/requests.rules.ts
src/modules/requests/requests.service.ts

- handling query params for search
- Title: feat: add search 
- Participants: @iqbal167 @ayocodingit @sandisunandar99 @rachadiannovansyah

feat: search

---

src/modules/requests/requests.controller.ts
src/modules/requests/requests.interface.ts
src/modules/requests/requests.rules.ts
src/modules/requests/requests.service.ts

- use single payload schema for patching data
- use single handler and service for handling update api
- inefficient api for patch every update progress
- refactor app config
- Title: feat: refactor update api
- Participants: @iqbal167 @ayocodingit @sandisunandar99

feat: refactor update api

---

LICENSE
README.md

- update documentation 
- Title: docs: update digiteam inventaris service documentation
- Participants: @iqbal167 @ayocodingit @sandisunandar99 @azophy

docs: update digiteam inventaris service documentation

---

src/modules/requests/requests.interface.ts
src/modules/requests/requests.rules.ts

- handling `pickup_date` value on backend
- add pickup date when status is received
- Title: feat: set pickup date
- Participants: @iqbal167 @ayocodingit @rindibudiaramdhan

feat: set pickup date

---

.github/workflows/continuous-deployment-staging.yml
src/common/helpers/upload.ts

- check file type and file size
- add unit test
- Title: fix: files upload response error
- Participants: @iqbal167 @ayocodingit @fajarhikmal214 @rhmnmbr83 @indraprasetya154 @liondy

fix: files upload response error

---

.github/workflows/continuous-deployment-staging.yml

- Fix undefined tag 
- Title: fix: tag staging
- Participants: @iqbal167 @liondy @ayocodingit

fix: tag staging

---

.github/workflows/continuous-deployment-staging.yml

Test:
- Title: fix: sha short commit
- Participants: @liondy @iqbal167 @ayocodingit

fix: sha short commit
